version: 0.2

phases:
  install:
    commands:
      # install Node 12
      - echo installing Node 12...
      - curl -sL https://deb.nodesource.com/setup_12.x | bash -
      - apt install -y nodejs

      # install Yarn
  pre_build:
    commmands:
      #install deps
      - echo installing deps...
      - npm i
  build:
    commands:
      #test
      - echo testing...
      #build
      - echo building...
      - npm run build
artifacts:
  files:
    - "**/*"
  discard-path: no
  base-directory: build